default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: students_dev 

test:
  <<: *default
  database: students_test

production:
  <<: *default
  database: students_production
  username: deployer
  password: 4EPTEHOK
